### ISSUE TITLE
set up denoise-ccs

### ISSUE THREAD

**Issue by v0369012** [sixvable/q2-dada2-CCS#1]
Hello! I replaced the old files (__init__.py, _denoise.py, plugin_setup.py, run_dada2_ccs.R) to your  new files for long reads.
Why can I sill not use the command `qiime dada2 denoise-ccs` ? Is there other settings? Thank you.

**Comment by sixvable** [comment]
Did you refresh your qiime2 environment after change those file？

`qiime dev refresh`

Show me the error log plz

**Comment by v0369012** [comment]
`Error:` QIIME 2 plugin 'dada2' has no action 'denoise-ccs'.`

I didn't know how to refresh my qiime2 in the beginning.
`qiime dev refresh` not work.
`Error: No such command 'refresh'`
Finally, I enter `qiime dev refresh-cache`, and it works.
Thanks for your reply!

**Comment by sixvable** [comment]
> Finally, I enter `qiime dev refresh-cache`, and it works.

Yes, that is what I actually mean. I re-write the README , you can check it again.
