### ISSUE TITLE
Change the files in python3.6 or python3.8

### ISSUE THREAD

**Issue by v0369012** [sixvable/q2-dada2-CCS#2]
Hello!
In your **Usage**, you said "Overwrite ... in /path/to/your/conda/envs/qiime2-version/lib/**python3.6**/site-packages/q2_dada2/ with the file in this repo."
However, in **Detail**, you said "Changing following files in /path/to/your/conda/envs/qiime2-version/lib/**python3.8**/site-packages/q2_dada2/"
Which is correct? I know QIIME2-2021.4 is using python 3.8, is it the reason? Thanks!

**Comment by sixvable** [comment]
forgot to change the README，use py3.8 right now
