### ISSUE TITLE
loss of many reads after dada2 denoise-ccs reads

### ISSUE THREAD

**Issue by Erique29** [sixvable/q2-dada2-CCS#3]
Hi @sixvable ,
I used this great PR to analyze my pacbio ccs, but around 70% reads were lost after denoise.  Is my parameters right ? or is it due to some other issues? 
My parameters were:
`qiime dada2 denoise-ccs --i-demultiplexed-seqs test.qza --p-min-len 1000 --p-max-len 1800 --o-table test_table.qza --o-representative-sequences test_seq.qza --o-denoising-stats test_stats.qza --p-front AGRGTTTGATYNTGGCTCAG --p-adapter TASGGHTACCTTGTTASGACTT --p-n-threads 0`
[test_stats.zip](https://github.com/sixvable/q2-dada2-CCS/files/7792076/test_stats.zip)
Thanks in advance!

**Comment by sixvable** [comment]
Problem Solved
