### ISSUE TITLE
 QIIME 2 plugin 'dada2' has no action 'denoise_css'

### ISSUE THREAD

**Issue by astrophys** [sixvable/q2-dada2-CCS#4]
I am using `QIIME2/2021.11` via `conda`.  I installed your edits according to USAGE section of your README.md.  

After activating the `conda` enironment, when I run :

```
$ qiime dada2 denoise-css
Error: QIIME 2 plugin 'dada2' has no action 'denoise-css'.
```

So I tried : 

```
$ qiime dada2 denoise_css
Error: QIIME 2 plugin 'dada2' has no action 'denoise_css'.
```

Question : 
1. How do I get your plugin to work?  Do I just run `run_dada_ccs.R` directly?

Thanks

**Comment by sixvable** [comment]
> I am using `QIIME2/2021.11`

I have **NOT** test my scripts on qiime2 version 2021.11, so probably its code has changed since 2021.4 . Maybe you should check the PRs to figure out what caused this failure.

**Comment by sixvable** [comment]
The QIIME2 v2022.2 is planned to officially support Pacbio CCS denoise action，check the NEWEST PRs and you can find the changes you need🎉
